name: Dart
#Name of the file

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  # This tells the Github when to run the file

jobs:
  #jobs - This is a group of steps
  # build, for example, is a name of a group
  build:
    runs-on: ubuntu-latest
    # This defines the environment for the actions to run on

    steps:
      #There are the steps

      - uses: actions/checkout@v4
      # this loads the code in the environment

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.5'
          channel: 'stable'
      #This downloads flutter

      - name: Install dependencies
        run: flutter pub get
        working-directory: note_app
      # This installs the dependecies
      # the working directory tells github in which folder it will find the pubspec.yaml

      - name: Analyze project source
        run: dart analyze
        working-directory: note_app
